package UI.GUI;

import java.util.Observable;
import java.util.Observer;
import movietime.ObservableApp;

public class MovieInfoPanel extends javax.swing.JPanel implements Observer {

    private ObservableApp observable;

    /**
     * Creates new form movieInfoPanel
     */
    public MovieInfoPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        releaseDateLabel = new javax.swing.JLabel();
        jlReleaseDate = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        directorLabel = new javax.swing.JLabel();
        mainActorsLabel = new javax.swing.JLabel();
        jlGenre = new javax.swing.JLabel();
        jlDirector = new javax.swing.JLabel();
        jlMainActors = new javax.swing.JLabel();
        jlMovieTitle = new javax.swing.JLabel();
        jbFollow = new javax.swing.JButton();
        jpMovieImage = new javax.swing.JPanel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        releaseDateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        releaseDateLabel.setText("Release date:");

        jlReleaseDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlReleaseDate.setText("[insert release date]");

        genreLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genreLabel.setText("Genre(s):");

        directorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        directorLabel.setText("Directed by:");

        mainActorsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainActorsLabel.setText("Main actors:");

        jlGenre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlGenre.setText("[insert genre(s)]");

        jlDirector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlDirector.setText("[insert director]");

        jlMainActors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlMainActors.setText("[insert main actors]");

        jlMovieTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlMovieTitle.setText("Movie title");

        jbFollow.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbFollow.setText("Follow");

        jpMovieImage.setMaximumSize(new java.awt.Dimension(120, 165));
        jpMovieImage.setMinimumSize(new java.awt.Dimension(120, 165));
        jpMovieImage.setPreferredSize(new java.awt.Dimension(120, 165));

        javax.swing.GroupLayout jpMovieImageLayout = new javax.swing.GroupLayout(jpMovieImage);
        jpMovieImage.setLayout(jpMovieImageLayout);
        jpMovieImageLayout.setHorizontalGroup(
            jpMovieImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jpMovieImageLayout.setVerticalGroup(
            jpMovieImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpMovieImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(releaseDateLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(genreLabel)
                                    .addGap(23, 23, 23))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mainActorsLabel)
                                    .addGap(7, 7, 7))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(directorLabel)
                                    .addGap(5, 5, 5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlReleaseDate)
                                    .addComponent(jlGenre)
                                    .addComponent(jlMainActors)
                                    .addComponent(jlDirector))
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbFollow)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlMovieTitle)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMovieTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlReleaseDate)
                        .addGap(35, 35, 35)
                        .addComponent(jlGenre)
                        .addGap(3, 3, 3)
                        .addComponent(jbFollow)
                        .addGap(4, 4, 4)
                        .addComponent(jlDirector)
                        .addGap(35, 35, 35)
                        .addComponent(jlMainActors))
                    .addComponent(jpMovieImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(releaseDateLabel)
                        .addGap(35, 35, 35)
                        .addComponent(genreLabel)
                        .addGap(30, 30, 30)
                        .addComponent(directorLabel)
                        .addGap(35, 35, 35)
                        .addComponent(mainActorsLabel)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel directorLabel;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JButton jbFollow;
    private javax.swing.JLabel jlDirector;
    private javax.swing.JLabel jlGenre;
    private javax.swing.JLabel jlMainActors;
    private javax.swing.JLabel jlMovieTitle;
    private javax.swing.JLabel jlReleaseDate;
    private javax.swing.JPanel jpMovieImage;
    private javax.swing.JLabel mainActorsLabel;
    private javax.swing.JLabel releaseDateLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        //TODO
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
