/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GUI;

/**
 *
 * @author salex
 */
public class NotificationSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationSettingsPanel
     */
    public NotificationSettingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarmFreqLabel = new javax.swing.JLabel();
        alarmFreq = new javax.swing.JTextField();
        shownInfoLabel = new javax.swing.JLabel();
        genre = new javax.swing.JCheckBox();
        director = new javax.swing.JCheckBox();
        mainActors = new javax.swing.JCheckBox();

        alarmFreqLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alarmFreqLabel.setText("Alarm frequency (days):");

        alarmFreq.setColumns(2);
        alarmFreq.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        shownInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        shownInfoLabel.setText("Info to be displayed:");

        genre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        genre.setText("Genre");

        director.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        director.setText("Director");
        director.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directorActionPerformed(evt);
            }
        });

        mainActors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mainActors.setText("Main actors");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alarmFreqLabel)
                    .addComponent(shownInfoLabel))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainActors)
                    .addComponent(director)
                    .addComponent(genre)
                    .addComponent(alarmFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alarmFreqLabel)
                    .addComponent(alarmFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shownInfoLabel)
                    .addComponent(genre))
                .addGap(18, 18, 18)
                .addComponent(director)
                .addGap(18, 18, 18)
                .addComponent(mainActors)
                .addContainerGap(169, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void directorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alarmFreq;
    private javax.swing.JLabel alarmFreqLabel;
    private javax.swing.JCheckBox director;
    private javax.swing.JCheckBox genre;
    private javax.swing.JCheckBox mainActors;
    private javax.swing.JLabel shownInfoLabel;
    // End of variables declaration//GEN-END:variables
}
