package UI.GUI;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import movietime.ObservableApp;


public class NotificationSettingsPanel extends javax.swing.JPanel implements Observer {
    
    private ObservableApp observable;

    /**
     * Creates new form NotificationSettingsPanel
     */
    public NotificationSettingsPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        initComponents();
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alarmFreqLabel = new javax.swing.JLabel();
        shownInfoLabel = new javax.swing.JLabel();
        jcbGenre = new javax.swing.JCheckBox();
        jcbDirector = new javax.swing.JCheckBox();
        jcbMainActors = new javax.swing.JCheckBox();
        jsDays = new javax.swing.JSpinner();
        bCancel = new javax.swing.JButton();
        bConfirm = new javax.swing.JButton();

        setBackground(new java.awt.Color(210, 180, 140));
        setMinimumSize(new java.awt.Dimension(850, 447));
        setOpaque(false);

        alarmFreqLabel.setBackground(null);
        alarmFreqLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        alarmFreqLabel.setForeground(new java.awt.Color(255, 255, 240));
        alarmFreqLabel.setText("Alarm frequency (days):");

        shownInfoLabel.setBackground(null);
        shownInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        shownInfoLabel.setForeground(new java.awt.Color(255, 255, 240));
        shownInfoLabel.setText("Info to be displayed:");

        jcbGenre.setBackground(null);
        jcbGenre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbGenre.setForeground(new java.awt.Color(255, 255, 240));
        jcbGenre.setText("Genre");
        jcbGenre.setIconTextGap(10);
        jcbGenre.setMaximumSize(new java.awt.Dimension(69, 31));
        jcbGenre.setMinimumSize(new java.awt.Dimension(69, 31));
        jcbGenre.setOpaque(false);

        jcbDirector.setBackground(null);
        jcbDirector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbDirector.setForeground(new java.awt.Color(255, 255, 240));
        jcbDirector.setText("Director");
        jcbDirector.setIconTextGap(10);
        jcbDirector.setMaximumSize(new java.awt.Dimension(69, 31));
        jcbDirector.setMinimumSize(new java.awt.Dimension(69, 31));
        jcbDirector.setOpaque(false);

        jcbMainActors.setBackground(null);
        jcbMainActors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbMainActors.setForeground(new java.awt.Color(255, 255, 240));
        jcbMainActors.setText("Main actors");
        jcbMainActors.setIconTextGap(10);
        jcbMainActors.setMaximumSize(new java.awt.Dimension(69, 31));
        jcbMainActors.setMinimumSize(new java.awt.Dimension(69, 31));
        jcbMainActors.setOpaque(false);

        jsDays.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bCancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bConfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bConfirm.setText("Confirm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alarmFreqLabel)
                            .addComponent(shownInfoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMainActors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsDays, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bCancel)
                        .addGap(18, 18, 18)
                        .addComponent(bConfirm)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alarmFreqLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsDays, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shownInfoLabel)
                    .addComponent(jcbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbMainActors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancel)
                    .addComponent(bConfirm))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        JOptionPane.showConfirmDialog(NotificationSettingsPanel.this,
                "Your changes will not be saved. Continue?",
                "Warning",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_bCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alarmFreqLabel;
    protected javax.swing.JButton bCancel;
    protected javax.swing.JButton bConfirm;
    protected javax.swing.JCheckBox jcbDirector;
    protected javax.swing.JCheckBox jcbGenre;
    protected javax.swing.JCheckBox jcbMainActors;
    protected javax.swing.JSpinner jsDays;
    private javax.swing.JLabel shownInfoLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        jsDays.setValue(observable.getDaysToAlert());
        jcbGenre.setSelected(observable.isGenreIncluded());
        jcbDirector.setSelected(observable.isDirectorIncluded());
        jcbMainActors.setSelected(observable.isCastIncluded());
    }
}
