/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Observable;
import java.util.Observer;
import movietime.ObservableApp;
import movietime.database.Movie;

/**
 *
 * @author sarah
 */
public class PreferredGenresRegisterPanel extends javax.swing.JPanel implements Observer {

    private ObservableApp observable;

    /**
     * Creates new form PreferredMoviesRegisterPanel
     */
    public PreferredGenresRegisterPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefGenresSelectionLabel = new javax.swing.JLabel();
        confirmPrefGenresButton = new javax.swing.JButton();
        jcbAction = new javax.swing.JCheckBox();
        jcbAdventure = new javax.swing.JCheckBox();
        jcbAnimation = new javax.swing.JCheckBox();
        jcbComedy = new javax.swing.JCheckBox();
        jcbCrime = new javax.swing.JCheckBox();
        jcbDocumentary = new javax.swing.JCheckBox();
        jcbDrama = new javax.swing.JCheckBox();
        jcbFamily = new javax.swing.JCheckBox();
        jcbFantasy = new javax.swing.JCheckBox();
        jcbWar = new javax.swing.JCheckBox();
        jcbHistory = new javax.swing.JCheckBox();
        jcbHorror = new javax.swing.JCheckBox();
        jcbMusic = new javax.swing.JCheckBox();
        jcbMystery = new javax.swing.JCheckBox();
        jcbRomance = new javax.swing.JCheckBox();
        jcbScienceFiction = new javax.swing.JCheckBox();
        jcbTVMovie = new javax.swing.JCheckBox();
        jcbThriller = new javax.swing.JCheckBox();
        jcbWestern = new javax.swing.JCheckBox();

        prefGenresSelectionLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        prefGenresSelectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prefGenresSelectionLabel.setText("Select your favourite movie genres");
        prefGenresSelectionLabel.setToolTipText("");
        prefGenresSelectionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prefGenresSelectionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        confirmPrefGenresButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmPrefGenresButton.setText("Confirm");

        jcbAction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbAction.setText("Action");

        jcbAdventure.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbAdventure.setText("Adventure");

        jcbAnimation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbAnimation.setText("Animation");

        jcbComedy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbComedy.setText("Comedy");

        jcbCrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbCrime.setText("Crime");

        jcbDocumentary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbDocumentary.setText("Documentary");

        jcbDrama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbDrama.setText("Drama");

        jcbFamily.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbFamily.setText("Family");

        jcbFantasy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbFantasy.setText("Fantasy");

        jcbWar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbWar.setText("War");

        jcbHistory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbHistory.setText("History");

        jcbHorror.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbHorror.setText("Horror");

        jcbMusic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMusic.setText("Music");

        jcbMystery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMystery.setText("Mystery");

        jcbRomance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbRomance.setText("Romance");

        jcbScienceFiction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbScienceFiction.setText("Science Fiction");

        jcbTVMovie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbTVMovie.setText("TV Movie");

        jcbThriller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbThriller.setText("Thriller");

        jcbWestern.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbWestern.setText("Western");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(prefGenresSelectionLabel)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmPrefGenresButton)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbComedy)
                            .addComponent(jcbAnimation)
                            .addComponent(jcbAdventure)
                            .addComponent(jcbAction)
                            .addComponent(jcbCrime))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbDocumentary)
                                    .addComponent(jcbDrama))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMusic)
                                    .addComponent(jcbHorror)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcbFantasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbFamily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMystery)
                                    .addComponent(jcbRomance)
                                    .addComponent(jcbScienceFiction))))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jcbThriller)
                                    .addGap(20, 20, 20))
                                .addComponent(jcbTVMovie)
                                .addComponent(jcbWestern))
                            .addComponent(jcbWar))
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(prefGenresSelectionLabel)
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAction)
                    .addComponent(jcbDocumentary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbHorror)
                    .addComponent(jcbThriller))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAdventure)
                    .addComponent(jcbDrama)
                    .addComponent(jcbMusic)
                    .addComponent(jcbTVMovie))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbFamily)
                            .addComponent(jcbAnimation)
                            .addComponent(jcbMystery)
                            .addComponent(jcbWestern))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbFantasy)
                            .addComponent(jcbComedy))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbCrime)
                            .addComponent(jcbHistory)
                            .addComponent(jcbScienceFiction)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbRomance)
                            .addComponent(jcbWar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134)
                .addComponent(confirmPrefGenresButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton confirmPrefGenresButton;
    protected javax.swing.JCheckBox jcbAction;
    protected javax.swing.JCheckBox jcbAdventure;
    protected javax.swing.JCheckBox jcbAnimation;
    protected javax.swing.JCheckBox jcbComedy;
    protected javax.swing.JCheckBox jcbCrime;
    protected javax.swing.JCheckBox jcbDocumentary;
    protected javax.swing.JCheckBox jcbDrama;
    protected javax.swing.JCheckBox jcbFamily;
    protected javax.swing.JCheckBox jcbFantasy;
    protected javax.swing.JCheckBox jcbHistory;
    protected javax.swing.JCheckBox jcbHorror;
    protected javax.swing.JCheckBox jcbMusic;
    protected javax.swing.JCheckBox jcbMystery;
    protected javax.swing.JCheckBox jcbRomance;
    protected javax.swing.JCheckBox jcbScienceFiction;
    protected javax.swing.JCheckBox jcbTVMovie;
    protected javax.swing.JCheckBox jcbThriller;
    protected javax.swing.JCheckBox jcbWar;
    protected javax.swing.JCheckBox jcbWestern;
    private javax.swing.JLabel prefGenresSelectionLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        //
    }
}
