/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;
import movietime.ObservableApp;

/**
 *
 * @author sarah
 */
public class PreferredGenresRegisterPanel extends javax.swing.JPanel implements Observer{

    private ObservableApp observable;
    /**
     * Creates new form PreferredMoviesRegisterPanel
     */
    public PreferredGenresRegisterPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        initComponents();
        
        confirmPrefGenresButton.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                String username = observable.getFirstName();
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefGenresSelectionLabel = new javax.swing.JLabel();
        confirmPrefGenresButton = new javax.swing.JButton();
        jcbAction = new javax.swing.JCheckBox();
        jcbAdventure = new javax.swing.JCheckBox();
        jcbAnimation = new javax.swing.JCheckBox();
        jcbComedy = new javax.swing.JCheckBox();
        jcbCrime = new javax.swing.JCheckBox();
        jcbDocumentary = new javax.swing.JCheckBox();
        jcbDrama = new javax.swing.JCheckBox();
        jcbFamily = new javax.swing.JCheckBox();
        jcbFantasy = new javax.swing.JCheckBox();
        jcbWar = new javax.swing.JCheckBox();
        jcbHistory = new javax.swing.JCheckBox();
        jcbHorror = new javax.swing.JCheckBox();
        jcbMusic = new javax.swing.JCheckBox();
        jcbMystery = new javax.swing.JCheckBox();
        jcbRomance = new javax.swing.JCheckBox();
        jcbScienceFiction = new javax.swing.JCheckBox();
        jcbTVMovie = new javax.swing.JCheckBox();
        jcbThriller = new javax.swing.JCheckBox();
        jcbWestern = new javax.swing.JCheckBox();

        prefGenresSelectionLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        prefGenresSelectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prefGenresSelectionLabel.setText("Select your favourite movie genres");
        prefGenresSelectionLabel.setToolTipText("");
        prefGenresSelectionLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prefGenresSelectionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        confirmPrefGenresButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        confirmPrefGenresButton.setText("Confirm");

        jcbAction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbAction.setText("Action");
        jcbAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbActionActionPerformed(evt);
            }
        });

        jcbAdventure.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbAdventure.setText("Adventure");
        jcbAdventure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAdventureActionPerformed(evt);
            }
        });

        jcbAnimation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbAnimation.setText("Animation");
        jcbAnimation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAnimationActionPerformed(evt);
            }
        });

        jcbComedy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbComedy.setText("Comedy");
        jcbComedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComedyActionPerformed(evt);
            }
        });

        jcbCrime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbCrime.setText("Crime");
        jcbCrime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCrimeActionPerformed(evt);
            }
        });

        jcbDocumentary.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbDocumentary.setText("Documentary");
        jcbDocumentary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDocumentaryActionPerformed(evt);
            }
        });

        jcbDrama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbDrama.setText("Drama");
        jcbDrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbDramaActionPerformed(evt);
            }
        });

        jcbFamily.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbFamily.setText("Family");
        jcbFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFamilyActionPerformed(evt);
            }
        });

        jcbFantasy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbFantasy.setText("Fantasy");
        jcbFantasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFantasyActionPerformed(evt);
            }
        });

        jcbWar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbWar.setText("War");
        jcbWar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbWarActionPerformed(evt);
            }
        });

        jcbHistory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbHistory.setText("History");
        jcbHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHistoryActionPerformed(evt);
            }
        });

        jcbHorror.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbHorror.setText("Horror");
        jcbHorror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHorrorActionPerformed(evt);
            }
        });

        jcbMusic.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMusic.setText("Music");
        jcbMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMusicActionPerformed(evt);
            }
        });

        jcbMystery.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMystery.setText("Mystery");
        jcbMystery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMysteryActionPerformed(evt);
            }
        });

        jcbRomance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbRomance.setText("Romance");
        jcbRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRomanceActionPerformed(evt);
            }
        });

        jcbScienceFiction.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbScienceFiction.setText("Science Fiction");
        jcbScienceFiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbScienceFictionActionPerformed(evt);
            }
        });

        jcbTVMovie.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbTVMovie.setText("TV Movie");
        jcbTVMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTVMovieActionPerformed(evt);
            }
        });

        jcbThriller.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbThriller.setText("Thriller");
        jcbThriller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbThrillerActionPerformed(evt);
            }
        });

        jcbWestern.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbWestern.setText("Western");
        jcbWestern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbWesternActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(prefGenresSelectionLabel)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmPrefGenresButton)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbComedy)
                            .addComponent(jcbAnimation)
                            .addComponent(jcbAdventure)
                            .addComponent(jcbAction)
                            .addComponent(jcbCrime))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbDocumentary)
                                    .addComponent(jcbDrama))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMusic)
                                    .addComponent(jcbHorror)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jcbFantasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbFamily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbMystery)
                                    .addComponent(jcbRomance)
                                    .addComponent(jcbScienceFiction))))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jcbThriller)
                                    .addGap(20, 20, 20))
                                .addComponent(jcbTVMovie)
                                .addComponent(jcbWestern))
                            .addComponent(jcbWar))
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(prefGenresSelectionLabel)
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAction)
                    .addComponent(jcbDocumentary, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbHorror)
                    .addComponent(jcbThriller))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAdventure)
                    .addComponent(jcbDrama)
                    .addComponent(jcbMusic)
                    .addComponent(jcbTVMovie))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbFamily)
                            .addComponent(jcbAnimation)
                            .addComponent(jcbMystery)
                            .addComponent(jcbWestern))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbFantasy)
                            .addComponent(jcbComedy))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbCrime)
                            .addComponent(jcbHistory)
                            .addComponent(jcbScienceFiction)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbRomance)
                            .addComponent(jcbWar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134)
                .addComponent(confirmPrefGenresButton)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbActionActionPerformed

    private void jcbAdventureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAdventureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAdventureActionPerformed

    private void jcbAnimationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAnimationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbAnimationActionPerformed

    private void jcbComedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComedyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbComedyActionPerformed

    private void jcbCrimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCrimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCrimeActionPerformed

    private void jcbDocumentaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDocumentaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDocumentaryActionPerformed

    private void jcbDramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbDramaActionPerformed

    private void jcbFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFamilyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFamilyActionPerformed

    private void jcbFantasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFantasyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbFantasyActionPerformed

    private void jcbWarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbWarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbWarActionPerformed

    private void jcbHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHistoryActionPerformed

    private void jcbHorrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHorrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHorrorActionPerformed

    private void jcbMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMusicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMusicActionPerformed

    private void jcbMysteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMysteryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMysteryActionPerformed

    private void jcbRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRomanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRomanceActionPerformed

    private void jcbScienceFictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbScienceFictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbScienceFictionActionPerformed

    private void jcbTVMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTVMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbTVMovieActionPerformed

    private void jcbThrillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbThrillerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbThrillerActionPerformed

    private void jcbWesternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbWesternActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbWesternActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmPrefGenresButton;
    private javax.swing.JCheckBox jcbAction;
    private javax.swing.JCheckBox jcbAdventure;
    private javax.swing.JCheckBox jcbAnimation;
    private javax.swing.JCheckBox jcbComedy;
    private javax.swing.JCheckBox jcbCrime;
    private javax.swing.JCheckBox jcbDocumentary;
    private javax.swing.JCheckBox jcbDrama;
    private javax.swing.JCheckBox jcbFamily;
    private javax.swing.JCheckBox jcbFantasy;
    private javax.swing.JCheckBox jcbHistory;
    private javax.swing.JCheckBox jcbHorror;
    private javax.swing.JCheckBox jcbMusic;
    private javax.swing.JCheckBox jcbMystery;
    private javax.swing.JCheckBox jcbRomance;
    private javax.swing.JCheckBox jcbScienceFiction;
    private javax.swing.JCheckBox jcbTVMovie;
    private javax.swing.JCheckBox jcbThriller;
    private javax.swing.JCheckBox jcbWar;
    private javax.swing.JCheckBox jcbWestern;
    private javax.swing.JLabel prefGenresSelectionLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        //TODO
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
