package UI.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import movietime.ObservableApp;
import movietime.authentication.UserAlreadyExistsException;
import movietime.authentication.UserDoesNotExistException;
import movietime.authentication.ValidationException;
import movietime.storage.OpeningFileException;
import movietime.storage.ReadWriteObjectException;


public class RegisterPanel extends javax.swing.JPanel implements Observer {

    private ObservableApp observable;
    
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        initComponents();
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameRegisterLabel = new javax.swing.JLabel();
        jtfUsername = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        jtfFirstName = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        jtfLastName = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(null);
        setPreferredSize(new java.awt.Dimension(550, 680));

        usernameRegisterLabel.setBackground(null);
        usernameRegisterLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        usernameRegisterLabel.setForeground(new java.awt.Color(207, 181, 59));
        usernameRegisterLabel.setText("Username");

        jtfUsername.setColumns(10);
        jtfUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfUsername.setForeground(new java.awt.Color(120, 120, 120));

        firstNameLabel.setBackground(null);
        firstNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(207, 181, 59));
        firstNameLabel.setText("First name");

        jtfFirstName.setColumns(10);
        jtfFirstName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfFirstName.setForeground(new java.awt.Color(120, 120, 120));

        lastNameLabel.setBackground(null);
        lastNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(207, 181, 59));
        lastNameLabel.setText("Last name");

        jtfLastName.setColumns(10);
        jtfLastName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfLastName.setForeground(new java.awt.Color(120, 120, 120));

        registerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        registerButton.setText("Register");

        jPanel1.setBackground(new java.awt.Color(120, 120, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(lastNameLabel)
                    .addComponent(usernameRegisterLabel))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameRegisterLabel)
                            .addComponent(jtfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel)
                            .addComponent(jtfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(jtfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JTextField jtfFirstName;
    protected javax.swing.JTextField jtfLastName;
    protected javax.swing.JTextField jtfUsername;
    private javax.swing.JLabel lastNameLabel;
    protected javax.swing.JButton registerButton;
    private javax.swing.JLabel usernameRegisterLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
    }
}
