package UI.GUI;

import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;
import movietime.ObservableApp;


public class SearchPanel extends javax.swing.JPanel implements Observer {
    private ObservableApp observable;

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        initComponents();
        ArrayList<String> genresList = observable.getStringGenres();
        for(String genre : genresList)
            jcbSelectGenre.addItem(genre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbSelectGenre = new javax.swing.JComboBox<>();
        jtfKeyword = new javax.swing.JTextField();
        jbSearch = new javax.swing.JButton();

        jcbSelectGenre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbSelectGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select genre" }));

        jtfKeyword.setColumns(10);
        jtfKeyword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtfKeyword.setText("Insert keyword");

        jbSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbSearch.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbSelectGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(jtfKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jbSearch)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbSelectGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbSearch;
    private javax.swing.JComboBox<String> jcbSelectGenre;
    private javax.swing.JTextField jtfKeyword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
    }
}
