package UI.GUI;

public class SideMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form SideMenuPanel
     */
    public SideMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPreferredMovies = new javax.swing.JButton();
        bUpcomingMovies = new javax.swing.JButton();
        bFollowedMovies = new javax.swing.JButton();
        bSettings = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();

        bPreferredMovies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bPreferredMovies.setText("Preferred movies");
        bPreferredMovies.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bUpcomingMovies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bUpcomingMovies.setText("Upcoming movies");
        bUpcomingMovies.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bFollowedMovies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bFollowedMovies.setText("Followed movies");
        bFollowedMovies.setActionCommand("");
        bFollowedMovies.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bSettings.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bSettings.setText("Settings");
        bSettings.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPreferredMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bUpcomingMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFollowedMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(bLogout)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(bPreferredMovies)
                .addGap(18, 18, 18)
                .addComponent(bFollowedMovies)
                .addGap(18, 18, 18)
                .addComponent(bUpcomingMovies)
                .addGap(18, 18, 18)
                .addComponent(bSettings)
                .addGap(58, 58, 58)
                .addComponent(bLogout)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFollowedMovies;
    protected javax.swing.JButton bLogout;
    private javax.swing.JButton bPreferredMovies;
    private javax.swing.JButton bSettings;
    private javax.swing.JButton bUpcomingMovies;
    // End of variables declaration//GEN-END:variables
}
