package UI.GUI;

public class SideMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form SideMenuPanel
     */
    public SideMenuPanel() {
        initComponents();
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPreferredMovies = new javax.swing.JButton();
        bUpcomingMovies = new javax.swing.JButton();
        bFollowedMovies = new javax.swing.JButton();
        bSettings = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        jlSideMenu = new javax.swing.JLabel();

        setBackground(null);
        setMaximumSize(null);

        bPreferredMovies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bPreferredMovies.setText("Preferred movies");
        bPreferredMovies.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bUpcomingMovies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bUpcomingMovies.setText("Upcoming movies");
        bUpcomingMovies.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bFollowedMovies.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bFollowedMovies.setText("Followed movies");
        bFollowedMovies.setActionCommand("");
        bFollowedMovies.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bSettings.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        bSettings.setText("Settings");
        bSettings.setMargin(new java.awt.Insets(10, 14, 10, 14));

        bLogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bLogout.setText("Logout");

        jlSideMenu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlSideMenu.setForeground(new java.awt.Color(255, 223, 0));
        jlSideMenu.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlSideMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bPreferredMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bUpcomingMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFollowedMovies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(bLogout)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlSideMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(bPreferredMovies)
                .addGap(18, 18, 18)
                .addComponent(bFollowedMovies)
                .addGap(18, 18, 18)
                .addComponent(bUpcomingMovies)
                .addGap(18, 18, 18)
                .addComponent(bSettings)
                .addGap(58, 58, 58)
                .addComponent(bLogout)
                .addGap(0, 161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton bFollowedMovies;
    protected javax.swing.JButton bLogout;
    protected javax.swing.JButton bPreferredMovies;
    protected javax.swing.JButton bSettings;
    protected javax.swing.JButton bUpcomingMovies;
    private javax.swing.JLabel jlSideMenu;
    // End of variables declaration//GEN-END:variables
}
