package UI.GUI;

public class UserInfoPanel extends javax.swing.JPanel {
    //TODO Observer

    /**
     * Creates new form UserInfoPanel
     */
    public UserInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSideMenu = new javax.swing.JLabel();
        jlFirstName = new javax.swing.JLabel();
        jlLastName = new javax.swing.JLabel();

        jlSideMenu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlSideMenu.setText("Menu");

        jlFirstName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlFirstName.setText("First name");

        jlLastName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlLastName.setText("Last name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlSideMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 715, Short.MAX_VALUE)
                .addComponent(jlFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlLastName)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSideMenu)
                    .addComponent(jlFirstName)
                    .addComponent(jlLastName))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlFirstName;
    private javax.swing.JLabel jlLastName;
    private javax.swing.JLabel jlSideMenu;
    // End of variables declaration//GEN-END:variables
}
