package UI.GUI;

import java.util.Observable;
import java.util.Observer;
import movietime.ObservableApp;

public class UserInfoPanel extends javax.swing.JPanel implements Observer{
    private ObservableApp observable;

    /**
     * Creates new form UserInfoPanel
     */
    public UserInfoPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSideMenu = new javax.swing.JLabel();
        jlFirstName = new javax.swing.JLabel();
        jlLastName = new javax.swing.JLabel();
        jlFirstName1 = new javax.swing.JLabel();

        jlSideMenu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlSideMenu.setText("Menu");

        jlFirstName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlFirstName.setText("First name");

        jlLastName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlLastName.setText("Last name");

        jlFirstName1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlFirstName1.setText("Hello,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlSideMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 584, Short.MAX_VALUE)
                .addComponent(jlFirstName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlLastName)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSideMenu)
                    .addComponent(jlFirstName)
                    .addComponent(jlLastName)
                    .addComponent(jlFirstName1))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlFirstName;
    private javax.swing.JLabel jlFirstName1;
    private javax.swing.JLabel jlLastName;
    private javax.swing.JLabel jlSideMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        jlFirstName.setText(observable.getFirstName());
        jlLastName.setText(observable.getLastName());
    }
}
