package UI.GUI;

import java.util.Observable;
import java.util.Observer;
import movietime.ObservableApp;

public class UserInfoPanel extends javax.swing.JPanel implements Observer{
    private ObservableApp observable;

    /**
     * Creates new form UserInfoPanel
     */
    public UserInfoPanel(ObservableApp obs) {
        observable = obs;
        observable.addObserver(this);
        
        initComponents();
        this.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFirstName = new javax.swing.JLabel();
        jlLastName = new javax.swing.JLabel();
        jlFirstName1 = new javax.swing.JLabel();

        setBackground(null);

        jlFirstName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jlFirstName.setForeground(new java.awt.Color(153, 101, 21));
        jlFirstName.setText("First name");

        jlLastName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jlLastName.setForeground(new java.awt.Color(153, 101, 21));
        jlLastName.setText("Last name");

        jlFirstName1.setBackground(new java.awt.Color(255, 250, 250));
        jlFirstName1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jlFirstName1.setForeground(new java.awt.Color(204, 204, 204));
        jlFirstName1.setText("hello,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(818, Short.MAX_VALUE)
                .addComponent(jlFirstName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlFirstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlLastName)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFirstName)
                    .addComponent(jlLastName)
                    .addComponent(jlFirstName1))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlFirstName;
    private javax.swing.JLabel jlFirstName1;
    private javax.swing.JLabel jlLastName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        jlFirstName.setText(observable.getFirstName());
        jlLastName.setText(observable.getLastName());
    }
}
